version: "3.3"

services:
#  Service -> Host name pre ostatne services
  database:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=event
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  fronend:
    build: ../event-FE
    ports:
      - "80"

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/event
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  data:
  logs: